import { useMemo, useState } from "react"
import { motion } from "framer-motion"

interface Props {
  narration: string
  workflow: string[]
}

interface Segment {
  range: string | null
  text: string
}

function parseNarration(raw: string): Segment[] {
  if (!raw) return []
  const re = /\[pic(\d+)-pic(\d+)\]/g
  const segments: Segment[] = []
  let lastIdx = 0
  let lastRange: string | null = null
  let m: RegExpExecArray | null
  while ((m = re.exec(raw))) {
    if (m.index > lastIdx) {
      const text = raw.slice(lastIdx, m.index).trim()
      if (text) segments.push({ range: lastRange, text })
    }
    lastRange = `${m[1]}–${m[2]}`
    lastIdx = m.index + m[0].length
  }
  const tail = raw.slice(lastIdx).trim()
  if (tail) segments.push({ range: lastRange, text: tail })
  return segments
}

export function NarrationPanel({ narration }: Props) {
  const [expanded, setExpanded] = useState(true)
  const segments = useMemo(() => parseNarration(narration), [narration])

  const headerSegment = segments[0]?.range === null ? segments[0] : null
  const body = headerSegment ? segments.slice(1) : segments

  return (
    <div className="card p-5">
      <div className="flex items-start justify-between gap-4 mb-3">
        <div>
          <div className="label">Think-aloud · LLM narration</div>
          <div className="text-sm text-ink-600 mt-0.5">
            Generated by Claude given the workflow screenshots and the task scenario.
          </div>
        </div>
        <button
          onClick={() => setExpanded((e) => !e)}
          className="btn-ghost text-xs"
        >
          {expanded ? "Collapse" : "Expand"}
        </button>
      </div>

      {headerSegment && (
        <div
          className="text-sm text-ink-700 mb-4"
          dangerouslySetInnerHTML={{ __html: renderInline(headerSegment.text) }}
        />
      )}

      {expanded && (
        <ol className="space-y-3">
          {body.map((seg, i) => (
            <motion.li
              key={i}
              initial={{ opacity: 0, x: -4 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, delay: i * 0.04 }}
              className="flex gap-3"
            >
              <div className="shrink-0">
                <span className="chip bg-accent-50 border-accent-200 text-accent-700 font-mono">
                  pic {seg.range}
                </span>
              </div>
              <div
                className="text-sm text-ink-700 leading-relaxed"
                dangerouslySetInnerHTML={{ __html: renderInline(seg.text) }}
              />
            </motion.li>
          ))}
        </ol>
      )}
    </div>
  )
}

function renderInline(text: string): string {
  // minimal markdown: **bold** and HTML entities (emojis come as &#x...)
  const escaped = text
    .replace(/&(?!#?\w+;)/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
  return escaped.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
}
